---

- name: Download FitNesse jar file
  get_url:
    url: "http://www.fitnesse.org/fitnesse-standalone.jar?responder=releaseDownload&release={{ fitnesse_version }}"
    dest: "{{ fitnesse.lib_dir }}/fitnesse-standalone.jar"
    owner: "{{ fitnesse.user_name }}"
    group: "{{ fitnesse.group_name }}"
    mode: 0440
  become: true
  tags:
    - fitnesse-setup
    - fitnesse-build-docker-image

- name: Download and install Xebium jar file
  get_url:
    url: "{{ fitnesse_xebium_download_url }}"
    dest: "{{ fitnesse.lib_dir }}/xebium.jar"
    owner: "{{ fitnesse.user_name }}"
    group: "{{ fitnesse.group_name }}"
    mode: 0440
  become: true
  when: fitnesse_get_xebium
  tags:
    - fitnesse-setup
    - fitnesse-build-docker-image
