---

- include: validate.yml
  tags:
    - always

- include: prepare.yml
  tags:
    - fitnesse-setup

- include: install.yml
  tags:
    - fitnesse-setup

- include: configure.yml
  tags:
    - fitnesse-setup

- include: service.yml

- include: browsers.yml
