---

#
# Run always
#

- name: Create fitnesse group
  group:
    name: "{{ fitnesse.group_name }}"
    gid: "{{ fitnesse.gid }}"
    system: yes
  become: yes
  tags:
    - always

- name: Create fitnesse user
  user:
    name: "{{ fitnesse.user_name }}"
    comment: 'FitNesse User'
    uid: "{{ fitnesse.uid }}"
    group: "{{ fitnesse.group_name }}"
    shell: /bin/bash
    home: "{{ fitnesse.home_dir }}"
    system: yes
  become: yes
  tags:
    - always

#
# Remove an existing container to prepare for a fresh install
#

- name: Remove fitnesse container
  docker:
    name: "{{ fitnesse_docker.ctn_name }}"
    image: "{{ fitnesse_docker.img_name }}"
    state: absent
  become: yes
  when: fitnesse_provision_mode == 'docker'
  tags:
    - fitnesse-remove-container
#
# Common tasks
#

- name: RedHat | Install dependency packages
  yum:
    name: "{{ item }}"
  with_items: "{{ fitnesse_pkg_depends.rh }}"
  become: yes
  when: ansible_os_family == 'RedHat'
  tags:
    - fitnesse-setup
    - fitnesse-build-docker-image

- name: Debian | Install dependency packages
  apt:
    name: "{{ item }}"
  with_items: "{{ fitnesse_pkg_depends.deb }}"
  become: yes
  when: ansible_os_family == 'Debian'
  tags:
    - fitnesse-setup
    - fitnesse-build-docker-image

- name: Create fitnesse lib directory
  file:
    path: "{{ fitnesse.lib_dir }}"
    owner: "{{ fitnesse.user_name }}"
    group: "{{ fitnesse.group_name }}"
    state: directory
  become: yes
  tags:
    - fitnesse-setup
    - fitnesse-build-docker-image
