---

- name: RedHat | Install dependency packages
  yum:
    name: "{{ item }}"
  with_items: "{{ fitnesse_pkg_depends.rh }}"
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Debian | Install dependency packages
  apt:
    name: "{{ item }}"
  with_items: "{{ fitnesse_pkg_depends.deb }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Create fitnesse group
  group:
    name: "{{ fitnesse.group_name }}"
    gid: "{{ fitnesse.gid }}"
    system: yes
  become: yes

- name: Create fitnesse user
  user:
    name: "{{ fitnesse.user_name }}"
    comment: 'FitNesse User'
    uid: "{{ fitnesse.uid }}"
    group: "{{ fitnesse.group_name }}"
    shell: /bin/bash
    home: "{{ fitnesse.home_dir }}"
    system: yes
  become: yes

- name: Create fitnesse lib directory
  file:
    path: "{{ fitnesse.lib_dir }}"
    owner: "{{ fitnesse.user_name }}"
    group: "{{ fitnesse.group_name }}"
    state: directory
  become: yes
